### ISSUE TITLE
Build fails due to phpCAS libs issue

### ISSUE THREAD

**Issue by fighne** [UniconLabs/dockerized-idp-testbed#24]
Error while building the current :latest

Step 3/14 : RUN git clone --depth=1 --branch=1.3.6 https://github.com/apereo/phpCAS.git apereo/phpCAS  && pear upgrade --force --alldeps  && cd apereo/phpCAS/utils  && pear install --onlyreqdeps PEAR_PackageFileManager2-beta  && ant dist -Ddoxygen.path=/usr/bin/doxygen -Dphp.path=/usr/bin/php
 ---> Running in 2eed41f8cd27
Cloning into 'apereo/phpCAS'...
Note: checking out '7972833e84f6ee5fa41f1479eab5d855109627f5'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b new_branch_name

No releases available for package "pear.php.net/structures_graph"
No releases available for package "pear.php.net/xml_util"
No releases available for package "pear.php.net/pear"
No releases available for package "pear.php.net/archive_tar"
No releases available for package "pear.php.net/console_getopt"
upgrade failed
ERROR: Service 'php-cas' failed to build: The command '/bin/sh -c git clone --depth=1 --branch=1.3.6 https://github.com/apereo/phpCAS.git apereo/phpCAS  && pear upgrade --force --alldeps  && cd apereo/phpCAS/utils  && pear install --onlyreqdeps PEAR_PackageFileManager2-beta  && ant dist -Ddoxygen.path=/usr/bin/doxygen -Dphp.path=/usr/bin/php' returned a non-zero code: 1

**Comment by nomadcanuck** [comment]
@fighne The first issue is it would appear there was a branch name convention change at [phpCAS](https://github.com/apereo/phpCAS.git), `--branch=1.3.6` does not exist. The git checkout will work if you change it to `--branch=1.3-stable`

The bigger issue is that [PEAR has been compromised](https://www.zdnet.com/article/mystery-still-surrounds-hack-of-php-pear-website/), which forced the developers to take down the php.net in its entirety. This includes pear.php.net which is why you see the `pear upgrade --force --alldeps` "upgrade failed".

You can still use this sample with the exception of _PHP App Protected by CAS hosted on Shibboleth IdP_.  In the **docker-compose.yml** comment out the _php-cas_ service:
```
#  php-cas:
#    build: ./php-cas/
#    links:
#      - httpd-proxy:idptestbed
#    networks:
#     - back
```

To get the _PHP App Protected by SimpleSAMLphp_ to work change `'privatekey' => 'server.pem',` to `'privatekey' => '/run/secrets/ssp_key',` in the **simplesamlphp/var-simplesamlphp/metadata/saml20-idp-hosted.php**

**Comment by jtgasper3** [comment]
I think the native cas php library is working once again. So I'm closing this out.
