### ISSUE TITLE
shibsp::ListenerException on linux

### ISSUE THREAD

**Issue by Ruturaj123** [UniconLabs/dockerized-idp-testbed#27]
Hi @jtgasper3 ,
Thank You for creating the dockerized idp and sp. 
While using this testbed, I found that none of the apps are working. When I open https://idptestbed it shows the 3 apps which we can test but each one of them is giving an error. 
PHP App Protected by Shibboleth SP -> shibsp::ListenerException
PHP App Protected by CAS hosted on Shibboleth IdP -> Service Unavailable
PHP App Protected by SimpleSAMLphp:
* Shibboleth IdP -> Service Unavailable
* SimpleSAMLphp IdP -> Unhandled Exception

Could you please help me out here as I am a newbie to Shibboleth.
Thank You

**Comment by VolodymyrBiryuk** [comment]
Same,
I get this whe I access the website it shows me

```
Hello World!
Apps:

PHP App Protected by Shibboleth SP
PHP App Protected by CAS hosted on Shibboleth IdP
PHP App Protected by SimpleSAMLphp
```

But none of the Apps work. Second and third gives "This site can’t be reached", first one shows:

```
shibsp::ListenerException
The system encountered an error at Tue Jul 2 14:34:32 2019

To report this problem, please contact the site administrator at admin@idptestbed.

Please include the following message in any email:

shibsp::ListenerException at (https://idptestbed/php-shib-protected/)

Cannot connect to shibd process, a site administrator should be notified that this web server has malfunctioned.
```

**Comment by carlosjm0325** [comment]
I've got all running except for the shibboleth sp (first app) - i do get a listener exception error.  What's odd though is that php-cas example works and I believe they connect to the same server.  Also, I tried from an external SP install and connecting and it connects fine.  Any progress on the specific error with "php-shib-protected" script?  This is an excellent testbed for new sso clients for my company and I'd love to get the solution for this.

**Comment by jtgasper3** [comment]
Hi @carlosjm0325,

I'm actually leaving Unicon and was hoping to get this project cleaned up before I go. (I've also asked permission to retain access to this project and the other related images, but we'll see what happens). 

Hopefully in the next day or so I'll have these working. I generally only use this for testing significant releases of the Shib IdP and SP as well as SSP, so it's not surprising that some stuff is broken. 

Let's see what I can get working... Also feel free to include any fixes you have and I'll get the PR merged in.

**Comment by jtgasper3** [comment]
> I've got all running except for the shibboleth sp (first app) - i do get a listener exception error. What's odd though is that php-cas example works and I believe they connect to the same server. Also, I tried from an external SP install and connecting and it connects fine. Any progress on the specific error with "php-shib-protected" script? This is an excellent testbed for new sso clients for my company and I'd love to get the solution for this.

So this solution runs multiple Apache httpd instances with the LB proxying to the others. In the case of the SP that Apache instance is complaining because it can't connect to the Shib SP daemon. (I'm working on that issue now.) so it returns an error to the LB Apache instance.

I'm not sure why the CAS protocol instance is failing. The IdP config definitely needs to get update to the modern equiv. That might be the ultimate fix there.

**Comment by jtgasper3** [comment]
This fixes the first issue: `docker pull unicon/shibboleth-sp:latest`
`down` the env first.

**Comment by carlosjm0325** [comment]
Just a quick note, you rock John!! - honestly didn't expect a response that fast! yeah, environment is killer and we're linking up with 160+ institutions with varying idp attributes and seemingly levels of integration (as well as ability/intelligence to integrate) so you've saved my life in more ways that one! Thanks for prompt attention.  And yeah, i'll push whatever i got fixed up but right now, no issues (especially if your push fixes up the sp) i've actually got things rocking using the independent package you created for the sp, was just working on volume perms so that i can share /etc/shib to host, then i see your message... #lifesaver :)

**Comment by jtgasper3** [comment]
Glad to hear it. For what it is worth, Unicon offers professional services around all of this stuff, if you find yourself in need of consulting help or someone to call at 2am when things are starting up properly.
