### ISSUE TITLE
Connection to the ldap server fails if the containers are re-upped 

### ISSUE THREAD

**Issue by febs** [UniconLabs/dockerized-idp-testbed#9]
How to reproduce:

build the images
"up" them
stop them with CTRL-C

"up" them again.
Now the IDP won't connect to the ldap.

**Comment by jtgasper3** [comment]
Hi @febs,

This is a known issue with the LDAP Server not gracefully stopping. Since this project is just a driver to do sanity testing of the Shibboleth IdP and SimpleSAMLphp docker images, I don't know that'll I'll be fixing it anytime soon, but feel free to work on it and submit a PR.

The workaround is to just call `docker-compose rm` before re-upping.

Thanks,
John
